package com.company.kanban.controller;
import com.company.kanban.dto.*; import com.company.kanban.entity.*; import com.company.kanban.service.DailyWorkReportService; import org.springframework.format.annotation.DateTimeFormat; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.time.LocalDate; import java.util.*;
@RestController @RequestMapping("/api/daily-reports")
public class DailyWorkReportController {
 private final DailyWorkReportService service; public DailyWorkReportController(DailyWorkReportService s){service=s;}
 @GetMapping("/today") public DailyReportViewResponse today(@AuthenticationPrincipal User u){return service.view(u,u.getId(),service.today());}
 @PutMapping("/today") public DailyReportViewResponse save(@AuthenticationPrincipal User u,@RequestBody DailyWorkReportRequest r){service.saveDraft(u,service.today(),r);return service.view(u,u.getId(),service.today());}
 @PostMapping("/today/submit") public DailyReportViewResponse submit(@AuthenticationPrincipal User u){service.submit(u,service.today());return service.view(u,u.getId(),service.today());}
 @GetMapping("/me") public DailyReportViewResponse me(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date){return service.view(u,u.getId(),date);}
 @GetMapping("/users/{userId}") public DailyReportViewResponse user(@AuthenticationPrincipal User u,@PathVariable Long userId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date){return service.view(u,userId,date);}
 @GetMapping("/users/{userId}/pdf") public ResponseEntity<byte[]> pdf(@AuthenticationPrincipal User u,@PathVariable Long userId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date){var v=service.view(u,userId,date);String name="FlowOps-"+v.employee().userName().replaceAll("[^A-Za-z0-9]+","-")+"-"+date+"-Daily-Report.pdf";return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+name+"\"").body(service.pdf(u,userId,date));}
 @GetMapping("/me/pdf") public ResponseEntity<byte[]> myPdf(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date){return pdf(u,u.getId(),date);}
 @GetMapping("/team/status") public List<Map<String,Object>> status(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date){return service.teamStatus(u,date);}
 @GetMapping("/team") public TeamDailyReportsResponse team(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date,@RequestParam(required=false) Long departmentId){return service.teamReports(u,date,departmentId);}
 @GetMapping("/availability") public List<Map<String,Object>> availability(@AuthenticationPrincipal User u,@RequestParam String month,@RequestParam(required=false) Long departmentId){return service.availability(u, java.time.YearMonth.parse(month), departmentId);}
 @GetMapping("/team/pdf") public ResponseEntity<byte[]> teamPdf(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate date,@RequestParam(required=false) Long departmentId){var pdf=service.teamPdf(u,date,departmentId);var scope=service.teamReports(u,date,departmentId);String name="FlowOps-"+scope.departmentName().replaceAll("[^A-Za-z0-9]+","-")+"-"+date+"-Team-Daily-Report.pdf";return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+name+"\"").body(pdf);}
 @GetMapping("/weekly") public WeeklyReportResponse weekly(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate weekStart,@RequestParam(required=false) Long departmentId){return service.weeklyReports(u,weekStart,departmentId);}
 @GetMapping("/weekly/pdf") public ResponseEntity<byte[]> weeklyPdf(@AuthenticationPrincipal User u,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE) LocalDate weekStart,@RequestParam(required=false) Long departmentId){var pdf=service.weeklyPdf(u,weekStart,departmentId);var report=service.weeklyReports(u,weekStart,departmentId);String name="FlowOps-"+report.departmentName().replaceAll("[^A-Za-z0-9]+","-")+"-"+report.weekStart()+"-Weekly-Report.pdf";return ResponseEntity.ok().contentType(MediaType.APPLICATION_PDF).header(HttpHeaders.CONTENT_DISPOSITION,"attachment; filename=\""+name+"\"").body(pdf);}
}
