import { useEffect, useState } from "react";
import { apiFetch } from "../api/apiFetch";
  const API = "";
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kuala_Lumpur" }).format(new Date());
const niceDate = (value) => value ? new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" }) : "";
function statusLabel(status) { return status === "SUBMITTED" ? "Submitted" : status === "DRAFT" ? "Draft" : "Not started"; }
export default function DailyReportPage({ user, selectedUserId, selectedDate, onBack, onViewSnapshot }) {
  const targetId = selectedUserId || user.userId; const date = selectedDate || today(); const isOwner = Number(targetId) === Number(user.userId); const editable = isOwner && date === today();
  const [report,setReport]=useState(null),[form,setForm]=useState({workSummary:"",blockers:"",nextDayPlan:""}),[state,setState]=useState("loading"),[message,setMessage]=useState("");
  const emptyView={employee:{userId:Number(targetId),userName:user.name||"You",departmentName:user.departmentName||""},report:{reportDate:date,reportStatus:"NOT_STARTED",workSummary:"",blockers:"",nextDayPlan:"",submittedAt:null},startOfDay:null,endOfDay:null,completedTasks:[],reviewTasks:[],activeTasks:[],startNote:"Start-of-day snapshot is not available.",endNote:"End-of-day snapshot is not available."};
  async function load(){setState("loading");try{const path=isOwner?`/api/daily-reports/me?date=${date}`:`/api/daily-reports/users/${targetId}?date=${date}`;const r=await apiFetch(API+path);if(r.status===404&&isOwner){setReport(emptyView);setForm({workSummary:"",blockers:"",nextDayPlan:""});setState("ready");return;}if(!r.ok)throw new Error(r.status===401?"Your session has expired. Please sign in again.":r.status===403?"You do not have permission to view this report.":r.status===404?"This report could not be found.":"Unable to load report.");const data=await r.json();setReport(data);setForm({workSummary:data.report.workSummary||"",blockers:data.report.blockers||"",nextDayPlan:data.report.nextDayPlan||""});setState("ready");}catch(e){setMessage(e.message);setState("error");}}
  useEffect(()=>{load();},[targetId,date]);
  async function save(submit=false){setMessage("");const draft=await apiFetch(`${API}/api/daily-reports/today`,{method:"PUT",body:JSON.stringify(form)});if(!draft.ok){setMessage(draft.status===403?"You do not have permission to edit this report.":draft.status===409?"This report is already submitted and read-only.":"Unable to save this report.");return;}let r=draft;if(submit){r=await apiFetch(`${API}/api/daily-reports/today/submit`,{method:"POST"});if(!r.ok){setMessage(r.status===403?"You do not have permission to submit this report.":"Unable to submit this report.");return;}}setReport(await r.json());setMessage(submit?"Report submitted and frozen.":"Draft saved.");}
  async function exportPdf(){const r=await apiFetch(`${API}${isOwner?`/api/daily-reports/me/pdf?date=${date}`:`/api/daily-reports/users/${targetId}/pdf?date=${date}`}`);if(!r.ok){setMessage("Unable to generate PDF.");return;}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`Kovax-FlowOps-${date}-Daily-Report.pdf`;a.click();URL.revokeObjectURL(url);}
  if(state==="loading")return <section className="dashboard-page"><p className="dashboard-status">Loading daily report...</p></section>;
  if(state==="error")return <section className="dashboard-page"><button className="text-button" onClick={onBack}>← Back</button><p className="dashboard-error">{message}</p></section>;
  const r=report.report, readOnly=!editable||r.reportStatus==="SUBMITTED";
  return <section className="dashboard-page daily-report-page"><div className="report-heading"><div><button className="text-button" onClick={onBack}>← Back</button><p className="eyebrow">Kovax FlowOps</p><h1>Daily Work Report</h1><p>{niceDate(r.reportDate)} · {report.employee.userName} · {report.employee.departmentName}</p></div><div className="report-actions"><span className={`report-status ${r.reportStatus.toLowerCase()}`}>{statusLabel(r.reportStatus)}</span><button className="secondary-button" onClick={exportPdf}>Export PDF</button></div></div>{message&&<p className="report-message">{message}</p>}{editable&&!readOnly?<div className="report-form"><Field label="Work completed / progress" value={form.workSummary} onChange={v=>setForm({...form,workSummary:v})} placeholder="Write a short sentence-style update about the work you completed or progressed today."/><Field label="Issues / blockers" value={form.blockers} onChange={v=>setForm({...form,blockers:v})} placeholder="Note anything that is blocked or needs attention."/><Field label="Plan for next working day" value={form.nextDayPlan} onChange={v=>setForm({...form,nextDayPlan:v})} placeholder="What do you plan to work on next?"/><p className="report-help">Your Kanban activity will be included automatically in the generated report.</p><div className="report-form-actions"><button className="secondary-button" onClick={()=>save(false)}>Save Draft</button><button className="primary-button" onClick={()=>{if(window.confirm("Submit today's report?\n\nThis will make the report read-only."))save(true)}}>Submit Report</button></div></div>:<Narrative report={r}/>}<WorkActivity report={report} onViewSnapshot={onViewSnapshot}/></section>;
}
function Field({label,value,onChange,placeholder}){return <label className="report-field"><span>{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} rows={5}/></label>}
function Narrative({report:r}){return <div className="report-narrative"><Block title="Work Summary" text={r.workSummary}/><Block title="Issues / Blockers" text={r.blockers}/><Block title="Next Working Day Plan" text={r.nextDayPlan}/></div>}
function Block({title,text}){return <div className="report-block"><h2>{title}</h2><p>{text||"No update provided."}</p></div>}
function WorkActivity({report,onViewSnapshot}){const s=report.startOfDay,e=report.endOfDay;return <div className="report-activity"><div className="report-section-heading"><h2>Task Activity</h2><button className="text-button" type="button" onClick={() => onViewSnapshot?.(report.employee.userId, report.report.reportDate)}>View Snapshot Details</button></div><div className="activity-grid"><Snapshot title="Start of Day" data={s} note={report.startNote}/><Snapshot title="End of Day" data={e} note={report.endNote}/></div><TaskList title="Completed Today" tasks={report.completedTasks}/><TaskList title="Moved to Review" tasks={report.reviewTasks}/><TaskList title="Still Active" tasks={report.activeTasks}/></div>}
function Snapshot({title,data,note}){return <div className="snapshot-card"><h3>{title}</h3>{data?<><div className="snapshot-stats"><span>Draft <b>{data.draftCount}</b></span><span>Doing <b>{data.doingCount}</b></span><span>Review <b>{data.reviewCount}</b></span><span>Done <b>{data.doneCount}</b></span></div><p>Active workload <strong>{data.activeWorkload}</strong></p>{data.recovered&&<small className="recovered-note">Recovered snapshot</small>}</>:<p className="dashboard-empty">{note}</p>}</div>}
function TaskList({title,tasks}){return <div className="report-task-section"><h2>{title}</h2>{tasks.length?<ul>{tasks.map(t=><li key={t.taskId}><span>{t.title}</span><small>{t.boardName} · Workload {t.workload??"—"}</small></li>)}</ul>:<p className="dashboard-empty">None</p>}</div>}
