import { useEffect, useMemo, useState } from "react";
import { apiFetch } from "../api/apiFetch";

const API = "http://localhost:8080";
const label = (value) => value ? new Date(value).toLocaleString(undefined, { day: "numeric", month: "short", hour: "numeric", minute: "2-digit" }) : "Recently";

export default function ReviewQueuePage({ onRefresh }) {
  const [items, setItems] = useState([]), [sort, setSort] = useState("oldest"), [state, setState] = useState("loading"), [message, setMessage] = useState("");
  async function load() { setState("loading"); try { const response = await apiFetch(`${API}/api/reviews`); if (!response.ok) throw new Error("Unable to load the review queue."); setItems(await response.json()); setState("ready"); } catch (e) { setMessage(e.message); setState("error"); } }
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => [...items].sort((a, b) => { const ad = new Date(a.submittedForReviewAt || a.updatedAt), bd = new Date(b.submittedForReviewAt || b.updatedAt); return sort === "newest" ? bd - ad : sort === "due" ? (a.dueDate || "9999").localeCompare(b.dueDate || "9999") : ad - bd; }), [items, sort]);
  async function action(item, actionName) { if (!window.confirm(actionName === "APPROVE" ? "Approve this task as Done?" : "Return this task to Doing?")) return; const response = await apiFetch(`${API}/api/tasks/${item.taskId}/review-action`, { method: "PUT", body: JSON.stringify({ action: actionName }) }); if (!response.ok) { setMessage("Unable to update this task."); return; } setItems((current) => current.filter((candidate) => candidate.taskId !== item.taskId)); onRefresh?.(); }
  if (state === "loading") return <section className="dashboard-page"><p className="dashboard-status">Loading reviews...</p></section>;
  if (state === "error") return <section className="dashboard-page"><p className="dashboard-error">{message}</p></section>;
  return <section className="dashboard-page review-queue-page"><div className="report-heading"><div><p className="eyebrow">Management action</p><h1>Reviews</h1><p>Tasks waiting for your decision.</p></div><label className="date-control">Sort <select value={sort} onChange={(e) => setSort(e.target.value)}><option value="oldest">Oldest first</option><option value="newest">Newest first</option><option value="due">Due soon first</option></select></label></div>{message && <p className="report-message">{message}</p>}<div className="kpi-grid"><div className="kpi-card warning"><span>Waiting for Review</span><strong>{items.length}</strong><small>Across your authorized scope</small></div></div><div className="review-queue-list">{visible.map((item) => <article className="review-queue-item" key={item.taskId}><div className="review-queue-copy"><h2>{item.title}</h2><p>{item.assigneeName || "Unassigned"} · {item.boardName || "No project"} · {item.departmentName || ""}</p><div className="review-meta"><span>Workload <b>{item.workload ?? "—"}</b></span><span>Priority <b>{item.priority}</b></span><span>Due <b>{item.dueDate || "—"}</b></span><span>Submitted <b>{label(item.submittedForReviewAt || item.updatedAt)}</b></span></div></div><div className="review-queue-actions"><button className="secondary-button" onClick={() => action(item, "RETURN")}>Return</button><button className="approve-button" onClick={() => action(item, "APPROVE")}>Approve</button></div></article>)}{!visible.length && <p className="dashboard-empty">Nothing is waiting for your decision.</p>}</div></section>;
}
